<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: rpc.proto

namespace Lnrpc;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>lnrpc.AMPRecord</code>
 */
class AMPRecord extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>bytes root_share = 1;</code>
     */
    private $root_share = '';
    /**
     * Generated from protobuf field <code>bytes set_id = 2;</code>
     */
    private $set_id = '';
    /**
     * Generated from protobuf field <code>uint32 child_index = 3;</code>
     */
    private $child_index = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $root_share
     *     @type string $set_id
     *     @type int $child_index
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Rpc::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>bytes root_share = 1;</code>
     * @return string
     */
    public function getRootShare()
    {
        return $this->root_share;
    }

    /**
     * Generated from protobuf field <code>bytes root_share = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setRootShare($var)
    {
        GPBUtil::checkString($var, False);
        $this->root_share = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bytes set_id = 2;</code>
     * @return string
     */
    public function getSetId()
    {
        return $this->set_id;
    }

    /**
     * Generated from protobuf field <code>bytes set_id = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setSetId($var)
    {
        GPBUtil::checkString($var, False);
        $this->set_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint32 child_index = 3;</code>
     * @return int
     */
    public function getChildIndex()
    {
        return $this->child_index;
    }

    /**
     * Generated from protobuf field <code>uint32 child_index = 3;</code>
     * @param int $var
     * @return $this
     */
    public function setChildIndex($var)
    {
        GPBUtil::checkUint32($var);
        $this->child_index = $var;

        return $this;
    }

}

