<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: lightning.proto

namespace Lnrpc;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>lnrpc.ChannelOpenUpdate</code>
 */
class ChannelOpenUpdate extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.lnrpc.ChannelPoint channel_point = 1;</code>
     */
    protected $channel_point = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Lnrpc\ChannelPoint $channel_point
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Lightning::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.lnrpc.ChannelPoint channel_point = 1;</code>
     * @return \Lnrpc\ChannelPoint|null
     */
    public function getChannelPoint()
    {
        return $this->channel_point;
    }

    public function hasChannelPoint()
    {
        return isset($this->channel_point);
    }

    public function clearChannelPoint()
    {
        unset($this->channel_point);
    }

    /**
     * Generated from protobuf field <code>.lnrpc.ChannelPoint channel_point = 1;</code>
     * @param \Lnrpc\ChannelPoint $var
     * @return $this
     */
    public function setChannelPoint($var)
    {
        GPBUtil::checkMessage($var, \Lnrpc\ChannelPoint::class);
        $this->channel_point = $var;

        return $this;
    }

}

