<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: rpc.proto

namespace Lnrpc;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>lnrpc.DeleteAllPaymentsRequest</code>
 */
class DeleteAllPaymentsRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Only delete failed payments.
     *
     * Generated from protobuf field <code>bool failed_payments_only = 1;</code>
     */
    private $failed_payments_only = false;
    /**
     *Only delete failed HTLCs from payments, not the payment itself.
     *
     * Generated from protobuf field <code>bool failed_htlcs_only = 2;</code>
     */
    private $failed_htlcs_only = false;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type bool $failed_payments_only
     *           Only delete failed payments.
     *     @type bool $failed_htlcs_only
     *          Only delete failed HTLCs from payments, not the payment itself.
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Rpc::initOnce();
        parent::__construct($data);
    }

    /**
     * Only delete failed payments.
     *
     * Generated from protobuf field <code>bool failed_payments_only = 1;</code>
     * @return bool
     */
    public function getFailedPaymentsOnly()
    {
        return $this->failed_payments_only;
    }

    /**
     * Only delete failed payments.
     *
     * Generated from protobuf field <code>bool failed_payments_only = 1;</code>
     * @param bool $var
     * @return $this
     */
    public function setFailedPaymentsOnly($var)
    {
        GPBUtil::checkBool($var);
        $this->failed_payments_only = $var;

        return $this;
    }

    /**
     *Only delete failed HTLCs from payments, not the payment itself.
     *
     * Generated from protobuf field <code>bool failed_htlcs_only = 2;</code>
     * @return bool
     */
    public function getFailedHtlcsOnly()
    {
        return $this->failed_htlcs_only;
    }

    /**
     *Only delete failed HTLCs from payments, not the payment itself.
     *
     * Generated from protobuf field <code>bool failed_htlcs_only = 2;</code>
     * @param bool $var
     * @return $this
     */
    public function setFailedHtlcsOnly($var)
    {
        GPBUtil::checkBool($var);
        $this->failed_htlcs_only = $var;

        return $this;
    }

}

