<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: rpc.proto

namespace Lnrpc;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>lnrpc.ForwardingEvent</code>
 */
class ForwardingEvent extends \Google\Protobuf\Internal\Message
{
    /**
     *&#47; Timestamp is the time (unix epoch offset) that this circuit was
     * / completed.
     *
     * Generated from protobuf field <code>uint64 timestamp = 1;</code>
     */
    private $timestamp = 0;
    /**
     *&#47; The incoming channel ID that carried the HTLC that created the circuit.
     *
     * Generated from protobuf field <code>uint64 chan_id_in = 2 [jstype = JS_STRING];</code>
     */
    private $chan_id_in = 0;
    /**
     *&#47; The outgoing channel ID that carried the preimage that completed the
     * / circuit.
     *
     * Generated from protobuf field <code>uint64 chan_id_out = 4 [jstype = JS_STRING];</code>
     */
    private $chan_id_out = 0;
    /**
     *&#47; The total amount (in satoshis) of the incoming HTLC that created half
     * / the circuit.
     *
     * Generated from protobuf field <code>uint64 amt_in = 5;</code>
     */
    private $amt_in = 0;
    /**
     *&#47; The total amount (in satoshis) of the outgoing HTLC that created the
     * / second half of the circuit.
     *
     * Generated from protobuf field <code>uint64 amt_out = 6;</code>
     */
    private $amt_out = 0;
    /**
     *&#47; The total fee (in satoshis) that this payment circuit carried.
     *
     * Generated from protobuf field <code>uint64 fee = 7;</code>
     */
    private $fee = 0;
    /**
     *&#47; The total fee (in milli-satoshis) that this payment circuit carried.
     *
     * Generated from protobuf field <code>uint64 fee_msat = 8;</code>
     */
    private $fee_msat = 0;
    /**
     *&#47; The total amount (in milli-satoshis) of the incoming HTLC that created
     * / half the circuit.
     *
     * Generated from protobuf field <code>uint64 amt_in_msat = 9;</code>
     */
    private $amt_in_msat = 0;
    /**
     *&#47; The total amount (in milli-satoshis) of the outgoing HTLC that created
     * / the second half of the circuit.
     *
     * Generated from protobuf field <code>uint64 amt_out_msat = 10;</code>
     */
    private $amt_out_msat = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int|string $timestamp
     *          &#47; Timestamp is the time (unix epoch offset) that this circuit was
     *          / completed.
     *     @type int|string $chan_id_in
     *          &#47; The incoming channel ID that carried the HTLC that created the circuit.
     *     @type int|string $chan_id_out
     *          &#47; The outgoing channel ID that carried the preimage that completed the
     *          / circuit.
     *     @type int|string $amt_in
     *          &#47; The total amount (in satoshis) of the incoming HTLC that created half
     *          / the circuit.
     *     @type int|string $amt_out
     *          &#47; The total amount (in satoshis) of the outgoing HTLC that created the
     *          / second half of the circuit.
     *     @type int|string $fee
     *          &#47; The total fee (in satoshis) that this payment circuit carried.
     *     @type int|string $fee_msat
     *          &#47; The total fee (in milli-satoshis) that this payment circuit carried.
     *     @type int|string $amt_in_msat
     *          &#47; The total amount (in milli-satoshis) of the incoming HTLC that created
     *          / half the circuit.
     *     @type int|string $amt_out_msat
     *          &#47; The total amount (in milli-satoshis) of the outgoing HTLC that created
     *          / the second half of the circuit.
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Rpc::initOnce();
        parent::__construct($data);
    }

    /**
     *&#47; Timestamp is the time (unix epoch offset) that this circuit was
     * / completed.
     *
     * Generated from protobuf field <code>uint64 timestamp = 1;</code>
     * @return int|string
     */
    public function getTimestamp()
    {
        return $this->timestamp;
    }

    /**
     *&#47; Timestamp is the time (unix epoch offset) that this circuit was
     * / completed.
     *
     * Generated from protobuf field <code>uint64 timestamp = 1;</code>
     * @param int|string $var
     * @return $this
     */
    public function setTimestamp($var)
    {
        GPBUtil::checkUint64($var);
        $this->timestamp = $var;

        return $this;
    }

    /**
     *&#47; The incoming channel ID that carried the HTLC that created the circuit.
     *
     * Generated from protobuf field <code>uint64 chan_id_in = 2 [jstype = JS_STRING];</code>
     * @return int|string
     */
    public function getChanIdIn()
    {
        return $this->chan_id_in;
    }

    /**
     *&#47; The incoming channel ID that carried the HTLC that created the circuit.
     *
     * Generated from protobuf field <code>uint64 chan_id_in = 2 [jstype = JS_STRING];</code>
     * @param int|string $var
     * @return $this
     */
    public function setChanIdIn($var)
    {
        GPBUtil::checkUint64($var);
        $this->chan_id_in = $var;

        return $this;
    }

    /**
     *&#47; The outgoing channel ID that carried the preimage that completed the
     * / circuit.
     *
     * Generated from protobuf field <code>uint64 chan_id_out = 4 [jstype = JS_STRING];</code>
     * @return int|string
     */
    public function getChanIdOut()
    {
        return $this->chan_id_out;
    }

    /**
     *&#47; The outgoing channel ID that carried the preimage that completed the
     * / circuit.
     *
     * Generated from protobuf field <code>uint64 chan_id_out = 4 [jstype = JS_STRING];</code>
     * @param int|string $var
     * @return $this
     */
    public function setChanIdOut($var)
    {
        GPBUtil::checkUint64($var);
        $this->chan_id_out = $var;

        return $this;
    }

    /**
     *&#47; The total amount (in satoshis) of the incoming HTLC that created half
     * / the circuit.
     *
     * Generated from protobuf field <code>uint64 amt_in = 5;</code>
     * @return int|string
     */
    public function getAmtIn()
    {
        return $this->amt_in;
    }

    /**
     *&#47; The total amount (in satoshis) of the incoming HTLC that created half
     * / the circuit.
     *
     * Generated from protobuf field <code>uint64 amt_in = 5;</code>
     * @param int|string $var
     * @return $this
     */
    public function setAmtIn($var)
    {
        GPBUtil::checkUint64($var);
        $this->amt_in = $var;

        return $this;
    }

    /**
     *&#47; The total amount (in satoshis) of the outgoing HTLC that created the
     * / second half of the circuit.
     *
     * Generated from protobuf field <code>uint64 amt_out = 6;</code>
     * @return int|string
     */
    public function getAmtOut()
    {
        return $this->amt_out;
    }

    /**
     *&#47; The total amount (in satoshis) of the outgoing HTLC that created the
     * / second half of the circuit.
     *
     * Generated from protobuf field <code>uint64 amt_out = 6;</code>
     * @param int|string $var
     * @return $this
     */
    public function setAmtOut($var)
    {
        GPBUtil::checkUint64($var);
        $this->amt_out = $var;

        return $this;
    }

    /**
     *&#47; The total fee (in satoshis) that this payment circuit carried.
     *
     * Generated from protobuf field <code>uint64 fee = 7;</code>
     * @return int|string
     */
    public function getFee()
    {
        return $this->fee;
    }

    /**
     *&#47; The total fee (in satoshis) that this payment circuit carried.
     *
     * Generated from protobuf field <code>uint64 fee = 7;</code>
     * @param int|string $var
     * @return $this
     */
    public function setFee($var)
    {
        GPBUtil::checkUint64($var);
        $this->fee = $var;

        return $this;
    }

    /**
     *&#47; The total fee (in milli-satoshis) that this payment circuit carried.
     *
     * Generated from protobuf field <code>uint64 fee_msat = 8;</code>
     * @return int|string
     */
    public function getFeeMsat()
    {
        return $this->fee_msat;
    }

    /**
     *&#47; The total fee (in milli-satoshis) that this payment circuit carried.
     *
     * Generated from protobuf field <code>uint64 fee_msat = 8;</code>
     * @param int|string $var
     * @return $this
     */
    public function setFeeMsat($var)
    {
        GPBUtil::checkUint64($var);
        $this->fee_msat = $var;

        return $this;
    }

    /**
     *&#47; The total amount (in milli-satoshis) of the incoming HTLC that created
     * / half the circuit.
     *
     * Generated from protobuf field <code>uint64 amt_in_msat = 9;</code>
     * @return int|string
     */
    public function getAmtInMsat()
    {
        return $this->amt_in_msat;
    }

    /**
     *&#47; The total amount (in milli-satoshis) of the incoming HTLC that created
     * / half the circuit.
     *
     * Generated from protobuf field <code>uint64 amt_in_msat = 9;</code>
     * @param int|string $var
     * @return $this
     */
    public function setAmtInMsat($var)
    {
        GPBUtil::checkUint64($var);
        $this->amt_in_msat = $var;

        return $this;
    }

    /**
     *&#47; The total amount (in milli-satoshis) of the outgoing HTLC that created
     * / the second half of the circuit.
     *
     * Generated from protobuf field <code>uint64 amt_out_msat = 10;</code>
     * @return int|string
     */
    public function getAmtOutMsat()
    {
        return $this->amt_out_msat;
    }

    /**
     *&#47; The total amount (in milli-satoshis) of the outgoing HTLC that created
     * / the second half of the circuit.
     *
     * Generated from protobuf field <code>uint64 amt_out_msat = 10;</code>
     * @param int|string $var
     * @return $this
     */
    public function setAmtOutMsat($var)
    {
        GPBUtil::checkUint64($var);
        $this->amt_out_msat = $var;

        return $this;
    }

}

