<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: lightning.proto

namespace Lnrpc;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>lnrpc.GetRecoveryInfoResponse</code>
 */
class GetRecoveryInfoResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * Whether the wallet is in recovery mode
     *
     * Generated from protobuf field <code>bool recovery_mode = 1;</code>
     */
    protected $recovery_mode = false;
    /**
     * Whether the wallet recovery progress is finished
     *
     * Generated from protobuf field <code>bool recovery_finished = 2;</code>
     */
    protected $recovery_finished = false;
    /**
     * The recovery progress, ranging from 0 to 1.
     *
     * Generated from protobuf field <code>double progress = 3;</code>
     */
    protected $progress = 0.0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type bool $recovery_mode
     *           Whether the wallet is in recovery mode
     *     @type bool $recovery_finished
     *           Whether the wallet recovery progress is finished
     *     @type float $progress
     *           The recovery progress, ranging from 0 to 1.
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Lightning::initOnce();
        parent::__construct($data);
    }

    /**
     * Whether the wallet is in recovery mode
     *
     * Generated from protobuf field <code>bool recovery_mode = 1;</code>
     * @return bool
     */
    public function getRecoveryMode()
    {
        return $this->recovery_mode;
    }

    /**
     * Whether the wallet is in recovery mode
     *
     * Generated from protobuf field <code>bool recovery_mode = 1;</code>
     * @param bool $var
     * @return $this
     */
    public function setRecoveryMode($var)
    {
        GPBUtil::checkBool($var);
        $this->recovery_mode = $var;

        return $this;
    }

    /**
     * Whether the wallet recovery progress is finished
     *
     * Generated from protobuf field <code>bool recovery_finished = 2;</code>
     * @return bool
     */
    public function getRecoveryFinished()
    {
        return $this->recovery_finished;
    }

    /**
     * Whether the wallet recovery progress is finished
     *
     * Generated from protobuf field <code>bool recovery_finished = 2;</code>
     * @param bool $var
     * @return $this
     */
    public function setRecoveryFinished($var)
    {
        GPBUtil::checkBool($var);
        $this->recovery_finished = $var;

        return $this;
    }

    /**
     * The recovery progress, ranging from 0 to 1.
     *
     * Generated from protobuf field <code>double progress = 3;</code>
     * @return float
     */
    public function getProgress()
    {
        return $this->progress;
    }

    /**
     * The recovery progress, ranging from 0 to 1.
     *
     * Generated from protobuf field <code>double progress = 3;</code>
     * @param float $var
     * @return $this
     */
    public function setProgress($var)
    {
        GPBUtil::checkDouble($var);
        $this->progress = $var;

        return $this;
    }

}

