<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: rpc.proto

namespace Lnrpc;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>lnrpc.LightningAddress</code>
 */
class LightningAddress extends \Google\Protobuf\Internal\Message
{
    /**
     * The identity pubkey of the Lightning node
     *
     * Generated from protobuf field <code>string pubkey = 1;</code>
     */
    protected $pubkey = '';
    /**
     * The network location of the lightning node, e.g. `69.69.69.69:1337` or
     * `localhost:10011`
     *
     * Generated from protobuf field <code>string host = 2;</code>
     */
    protected $host = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $pubkey
     *           The identity pubkey of the Lightning node
     *     @type string $host
     *           The network location of the lightning node, e.g. `69.69.69.69:1337` or
     *           `localhost:10011`
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Rpc::initOnce();
        parent::__construct($data);
    }

    /**
     * The identity pubkey of the Lightning node
     *
     * Generated from protobuf field <code>string pubkey = 1;</code>
     * @return string
     */
    public function getPubkey()
    {
        return $this->pubkey;
    }

    /**
     * The identity pubkey of the Lightning node
     *
     * Generated from protobuf field <code>string pubkey = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setPubkey($var)
    {
        GPBUtil::checkString($var, True);
        $this->pubkey = $var;

        return $this;
    }

    /**
     * The network location of the lightning node, e.g. `69.69.69.69:1337` or
     * `localhost:10011`
     *
     * Generated from protobuf field <code>string host = 2;</code>
     * @return string
     */
    public function getHost()
    {
        return $this->host;
    }

    /**
     * The network location of the lightning node, e.g. `69.69.69.69:1337` or
     * `localhost:10011`
     *
     * Generated from protobuf field <code>string host = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setHost($var)
    {
        GPBUtil::checkString($var, True);
        $this->host = $var;

        return $this;
    }

}

