<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: lightning.proto

namespace Lnrpc;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>lnrpc.ListPeersResponse</code>
 */
class ListPeersResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * The list of currently connected peers
     *
     * Generated from protobuf field <code>repeated .lnrpc.Peer peers = 1;</code>
     */
    private $peers;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type array<\Lnrpc\Peer>|\Google\Protobuf\Internal\RepeatedField $peers
     *           The list of currently connected peers
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Lightning::initOnce();
        parent::__construct($data);
    }

    /**
     * The list of currently connected peers
     *
     * Generated from protobuf field <code>repeated .lnrpc.Peer peers = 1;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getPeers()
    {
        return $this->peers;
    }

    /**
     * The list of currently connected peers
     *
     * Generated from protobuf field <code>repeated .lnrpc.Peer peers = 1;</code>
     * @param array<\Lnrpc\Peer>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setPeers($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Lnrpc\Peer::class);
        $this->peers = $arr;

        return $this;
    }

}

