<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: lightning.proto

namespace Lnrpc;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>lnrpc.ListChannelsRequest</code>
 */
class ListChannelsRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>bool active_only = 1;</code>
     */
    protected $active_only = false;
    /**
     * Generated from protobuf field <code>bool inactive_only = 2;</code>
     */
    protected $inactive_only = false;
    /**
     * Generated from protobuf field <code>bool public_only = 3;</code>
     */
    protected $public_only = false;
    /**
     * Generated from protobuf field <code>bool private_only = 4;</code>
     */
    protected $private_only = false;
    /**
     *Filters the response for channels with a target peer's pubkey. If peer is
     *empty, all channels will be returned.
     *
     * Generated from protobuf field <code>bytes peer = 5;</code>
     */
    protected $peer = '';
    /**
     * Informs the server if the peer alias lookup per channel should be
     * enabled. It is turned off by default in order to avoid degradation of
     * performance for existing clients.
     *
     * Generated from protobuf field <code>bool peer_alias_lookup = 6;</code>
     */
    protected $peer_alias_lookup = false;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type bool $active_only
     *     @type bool $inactive_only
     *     @type bool $public_only
     *     @type bool $private_only
     *     @type string $peer
     *          Filters the response for channels with a target peer's pubkey. If peer is
     *          empty, all channels will be returned.
     *     @type bool $peer_alias_lookup
     *           Informs the server if the peer alias lookup per channel should be
     *           enabled. It is turned off by default in order to avoid degradation of
     *           performance for existing clients.
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Lightning::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>bool active_only = 1;</code>
     * @return bool
     */
    public function getActiveOnly()
    {
        return $this->active_only;
    }

    /**
     * Generated from protobuf field <code>bool active_only = 1;</code>
     * @param bool $var
     * @return $this
     */
    public function setActiveOnly($var)
    {
        GPBUtil::checkBool($var);
        $this->active_only = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool inactive_only = 2;</code>
     * @return bool
     */
    public function getInactiveOnly()
    {
        return $this->inactive_only;
    }

    /**
     * Generated from protobuf field <code>bool inactive_only = 2;</code>
     * @param bool $var
     * @return $this
     */
    public function setInactiveOnly($var)
    {
        GPBUtil::checkBool($var);
        $this->inactive_only = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool public_only = 3;</code>
     * @return bool
     */
    public function getPublicOnly()
    {
        return $this->public_only;
    }

    /**
     * Generated from protobuf field <code>bool public_only = 3;</code>
     * @param bool $var
     * @return $this
     */
    public function setPublicOnly($var)
    {
        GPBUtil::checkBool($var);
        $this->public_only = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool private_only = 4;</code>
     * @return bool
     */
    public function getPrivateOnly()
    {
        return $this->private_only;
    }

    /**
     * Generated from protobuf field <code>bool private_only = 4;</code>
     * @param bool $var
     * @return $this
     */
    public function setPrivateOnly($var)
    {
        GPBUtil::checkBool($var);
        $this->private_only = $var;

        return $this;
    }

    /**
     *Filters the response for channels with a target peer's pubkey. If peer is
     *empty, all channels will be returned.
     *
     * Generated from protobuf field <code>bytes peer = 5;</code>
     * @return string
     */
    public function getPeer()
    {
        return $this->peer;
    }

    /**
     *Filters the response for channels with a target peer's pubkey. If peer is
     *empty, all channels will be returned.
     *
     * Generated from protobuf field <code>bytes peer = 5;</code>
     * @param string $var
     * @return $this
     */
    public function setPeer($var)
    {
        GPBUtil::checkString($var, False);
        $this->peer = $var;

        return $this;
    }

    /**
     * Informs the server if the peer alias lookup per channel should be
     * enabled. It is turned off by default in order to avoid degradation of
     * performance for existing clients.
     *
     * Generated from protobuf field <code>bool peer_alias_lookup = 6;</code>
     * @return bool
     */
    public function getPeerAliasLookup()
    {
        return $this->peer_alias_lookup;
    }

    /**
     * Informs the server if the peer alias lookup per channel should be
     * enabled. It is turned off by default in order to avoid degradation of
     * performance for existing clients.
     *
     * Generated from protobuf field <code>bool peer_alias_lookup = 6;</code>
     * @param bool $var
     * @return $this
     */
    public function setPeerAliasLookup($var)
    {
        GPBUtil::checkBool($var);
        $this->peer_alias_lookup = $var;

        return $this;
    }

}

