<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: lightning.proto

namespace Lnrpc;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>lnrpc.ListAliasesResponse</code>
 */
class ListAliasesResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>repeated .lnrpc.AliasMap alias_maps = 1;</code>
     */
    private $alias_maps;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type array<\Lnrpc\AliasMap>|\Google\Protobuf\Internal\RepeatedField $alias_maps
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Lightning::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>repeated .lnrpc.AliasMap alias_maps = 1;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getAliasMaps()
    {
        return $this->alias_maps;
    }

    /**
     * Generated from protobuf field <code>repeated .lnrpc.AliasMap alias_maps = 1;</code>
     * @param array<\Lnrpc\AliasMap>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setAliasMaps($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Lnrpc\AliasMap::class);
        $this->alias_maps = $arr;

        return $this;
    }

}

