<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: lightning.proto

namespace Lnrpc;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>lnrpc.LookupHtlcResolutionResponse</code>
 */
class LookupHtlcResolutionResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * Settled is true is the htlc was settled. If false, the htlc was failed.
     *
     * Generated from protobuf field <code>bool settled = 1;</code>
     */
    protected $settled = false;
    /**
     * Offchain indicates whether the htlc was resolved off-chain or on-chain.
     *
     * Generated from protobuf field <code>bool offchain = 2;</code>
     */
    protected $offchain = false;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type bool $settled
     *           Settled is true is the htlc was settled. If false, the htlc was failed.
     *     @type bool $offchain
     *           Offchain indicates whether the htlc was resolved off-chain or on-chain.
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Lightning::initOnce();
        parent::__construct($data);
    }

    /**
     * Settled is true is the htlc was settled. If false, the htlc was failed.
     *
     * Generated from protobuf field <code>bool settled = 1;</code>
     * @return bool
     */
    public function getSettled()
    {
        return $this->settled;
    }

    /**
     * Settled is true is the htlc was settled. If false, the htlc was failed.
     *
     * Generated from protobuf field <code>bool settled = 1;</code>
     * @param bool $var
     * @return $this
     */
    public function setSettled($var)
    {
        GPBUtil::checkBool($var);
        $this->settled = $var;

        return $this;
    }

    /**
     * Offchain indicates whether the htlc was resolved off-chain or on-chain.
     *
     * Generated from protobuf field <code>bool offchain = 2;</code>
     * @return bool
     */
    public function getOffchain()
    {
        return $this->offchain;
    }

    /**
     * Offchain indicates whether the htlc was resolved off-chain or on-chain.
     *
     * Generated from protobuf field <code>bool offchain = 2;</code>
     * @param bool $var
     * @return $this
     */
    public function setOffchain($var)
    {
        GPBUtil::checkBool($var);
        $this->offchain = $var;

        return $this;
    }

}

