<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: lightning.proto

namespace Lnrpc;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>lnrpc.NetworkInfo</code>
 */
class NetworkInfo extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>uint32 graph_diameter = 1;</code>
     */
    protected $graph_diameter = 0;
    /**
     * Generated from protobuf field <code>double avg_out_degree = 2;</code>
     */
    protected $avg_out_degree = 0.0;
    /**
     * Generated from protobuf field <code>uint32 max_out_degree = 3;</code>
     */
    protected $max_out_degree = 0;
    /**
     * Generated from protobuf field <code>uint32 num_nodes = 4;</code>
     */
    protected $num_nodes = 0;
    /**
     * Generated from protobuf field <code>uint32 num_channels = 5;</code>
     */
    protected $num_channels = 0;
    /**
     * Generated from protobuf field <code>int64 total_network_capacity = 6;</code>
     */
    protected $total_network_capacity = 0;
    /**
     * Generated from protobuf field <code>double avg_channel_size = 7;</code>
     */
    protected $avg_channel_size = 0.0;
    /**
     * Generated from protobuf field <code>int64 min_channel_size = 8;</code>
     */
    protected $min_channel_size = 0;
    /**
     * Generated from protobuf field <code>int64 max_channel_size = 9;</code>
     */
    protected $max_channel_size = 0;
    /**
     * Generated from protobuf field <code>int64 median_channel_size_sat = 10;</code>
     */
    protected $median_channel_size_sat = 0;
    /**
     * The number of edges marked as zombies.
     *
     * Generated from protobuf field <code>uint64 num_zombie_chans = 11;</code>
     */
    protected $num_zombie_chans = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $graph_diameter
     *     @type float $avg_out_degree
     *     @type int $max_out_degree
     *     @type int $num_nodes
     *     @type int $num_channels
     *     @type int|string $total_network_capacity
     *     @type float $avg_channel_size
     *     @type int|string $min_channel_size
     *     @type int|string $max_channel_size
     *     @type int|string $median_channel_size_sat
     *     @type int|string $num_zombie_chans
     *           The number of edges marked as zombies.
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Lightning::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>uint32 graph_diameter = 1;</code>
     * @return int
     */
    public function getGraphDiameter()
    {
        return $this->graph_diameter;
    }

    /**
     * Generated from protobuf field <code>uint32 graph_diameter = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setGraphDiameter($var)
    {
        GPBUtil::checkUint32($var);
        $this->graph_diameter = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>double avg_out_degree = 2;</code>
     * @return float
     */
    public function getAvgOutDegree()
    {
        return $this->avg_out_degree;
    }

    /**
     * Generated from protobuf field <code>double avg_out_degree = 2;</code>
     * @param float $var
     * @return $this
     */
    public function setAvgOutDegree($var)
    {
        GPBUtil::checkDouble($var);
        $this->avg_out_degree = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint32 max_out_degree = 3;</code>
     * @return int
     */
    public function getMaxOutDegree()
    {
        return $this->max_out_degree;
    }

    /**
     * Generated from protobuf field <code>uint32 max_out_degree = 3;</code>
     * @param int $var
     * @return $this
     */
    public function setMaxOutDegree($var)
    {
        GPBUtil::checkUint32($var);
        $this->max_out_degree = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint32 num_nodes = 4;</code>
     * @return int
     */
    public function getNumNodes()
    {
        return $this->num_nodes;
    }

    /**
     * Generated from protobuf field <code>uint32 num_nodes = 4;</code>
     * @param int $var
     * @return $this
     */
    public function setNumNodes($var)
    {
        GPBUtil::checkUint32($var);
        $this->num_nodes = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint32 num_channels = 5;</code>
     * @return int
     */
    public function getNumChannels()
    {
        return $this->num_channels;
    }

    /**
     * Generated from protobuf field <code>uint32 num_channels = 5;</code>
     * @param int $var
     * @return $this
     */
    public function setNumChannels($var)
    {
        GPBUtil::checkUint32($var);
        $this->num_channels = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 total_network_capacity = 6;</code>
     * @return int|string
     */
    public function getTotalNetworkCapacity()
    {
        return $this->total_network_capacity;
    }

    /**
     * Generated from protobuf field <code>int64 total_network_capacity = 6;</code>
     * @param int|string $var
     * @return $this
     */
    public function setTotalNetworkCapacity($var)
    {
        GPBUtil::checkInt64($var);
        $this->total_network_capacity = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>double avg_channel_size = 7;</code>
     * @return float
     */
    public function getAvgChannelSize()
    {
        return $this->avg_channel_size;
    }

    /**
     * Generated from protobuf field <code>double avg_channel_size = 7;</code>
     * @param float $var
     * @return $this
     */
    public function setAvgChannelSize($var)
    {
        GPBUtil::checkDouble($var);
        $this->avg_channel_size = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 min_channel_size = 8;</code>
     * @return int|string
     */
    public function getMinChannelSize()
    {
        return $this->min_channel_size;
    }

    /**
     * Generated from protobuf field <code>int64 min_channel_size = 8;</code>
     * @param int|string $var
     * @return $this
     */
    public function setMinChannelSize($var)
    {
        GPBUtil::checkInt64($var);
        $this->min_channel_size = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 max_channel_size = 9;</code>
     * @return int|string
     */
    public function getMaxChannelSize()
    {
        return $this->max_channel_size;
    }

    /**
     * Generated from protobuf field <code>int64 max_channel_size = 9;</code>
     * @param int|string $var
     * @return $this
     */
    public function setMaxChannelSize($var)
    {
        GPBUtil::checkInt64($var);
        $this->max_channel_size = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 median_channel_size_sat = 10;</code>
     * @return int|string
     */
    public function getMedianChannelSizeSat()
    {
        return $this->median_channel_size_sat;
    }

    /**
     * Generated from protobuf field <code>int64 median_channel_size_sat = 10;</code>
     * @param int|string $var
     * @return $this
     */
    public function setMedianChannelSizeSat($var)
    {
        GPBUtil::checkInt64($var);
        $this->median_channel_size_sat = $var;

        return $this;
    }

    /**
     * The number of edges marked as zombies.
     *
     * Generated from protobuf field <code>uint64 num_zombie_chans = 11;</code>
     * @return int|string
     */
    public function getNumZombieChans()
    {
        return $this->num_zombie_chans;
    }

    /**
     * The number of edges marked as zombies.
     *
     * Generated from protobuf field <code>uint64 num_zombie_chans = 11;</code>
     * @param int|string $var
     * @return $this
     */
    public function setNumZombieChans($var)
    {
        GPBUtil::checkUint64($var);
        $this->num_zombie_chans = $var;

        return $this;
    }

}

