<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: rpc.proto

namespace Lnrpc;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>lnrpc.NewAddressRequest</code>
 */
class NewAddressRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * The type of address to generate.
     *
     * Generated from protobuf field <code>.lnrpc.AddressType type = 1;</code>
     */
    private $type = 0;
    /**
     *The name of the account to generate a new address for. If empty, the
     *default wallet account is used.
     *
     * Generated from protobuf field <code>string account = 2;</code>
     */
    private $account = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $type
     *           The type of address to generate.
     *     @type string $account
     *          The name of the account to generate a new address for. If empty, the
     *          default wallet account is used.
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Rpc::initOnce();
        parent::__construct($data);
    }

    /**
     * The type of address to generate.
     *
     * Generated from protobuf field <code>.lnrpc.AddressType type = 1;</code>
     * @return int
     */
    public function getType()
    {
        return $this->type;
    }

    /**
     * The type of address to generate.
     *
     * Generated from protobuf field <code>.lnrpc.AddressType type = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setType($var)
    {
        GPBUtil::checkEnum($var, \Lnrpc\AddressType::class);
        $this->type = $var;

        return $this;
    }

    /**
     *The name of the account to generate a new address for. If empty, the
     *default wallet account is used.
     *
     * Generated from protobuf field <code>string account = 2;</code>
     * @return string
     */
    public function getAccount()
    {
        return $this->account;
    }

    /**
     *The name of the account to generate a new address for. If empty, the
     *default wallet account is used.
     *
     * Generated from protobuf field <code>string account = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setAccount($var)
    {
        GPBUtil::checkString($var, True);
        $this->account = $var;

        return $this;
    }

}

