<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: rpc.proto

namespace Lnrpc;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>lnrpc.PsbtShim</code>
 */
class PsbtShim extends \Google\Protobuf\Internal\Message
{
    /**
     *A unique identifier of 32 random bytes that will be used as the pending
     *channel ID to identify the PSBT state machine when interacting with it and
     *on the wire protocol to initiate the funding request.
     *
     * Generated from protobuf field <code>bytes pending_chan_id = 1;</code>
     */
    private $pending_chan_id = '';
    /**
     *An optional base PSBT the new channel output will be added to. If this is
     *non-empty, it must be a binary serialized PSBT.
     *
     * Generated from protobuf field <code>bytes base_psbt = 2;</code>
     */
    private $base_psbt = '';
    /**
     *If a channel should be part of a batch (multiple channel openings in one
     *transaction), it can be dangerous if the whole batch transaction is
     *published too early before all channel opening negotiations are completed.
     *This flag prevents this particular channel from broadcasting the transaction
     *after the negotiation with the remote peer. In a batch of channel openings
     *this flag should be set to true for every channel but the very last.
     *
     * Generated from protobuf field <code>bool no_publish = 3;</code>
     */
    private $no_publish = false;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $pending_chan_id
     *          A unique identifier of 32 random bytes that will be used as the pending
     *          channel ID to identify the PSBT state machine when interacting with it and
     *          on the wire protocol to initiate the funding request.
     *     @type string $base_psbt
     *          An optional base PSBT the new channel output will be added to. If this is
     *          non-empty, it must be a binary serialized PSBT.
     *     @type bool $no_publish
     *          If a channel should be part of a batch (multiple channel openings in one
     *          transaction), it can be dangerous if the whole batch transaction is
     *          published too early before all channel opening negotiations are completed.
     *          This flag prevents this particular channel from broadcasting the transaction
     *          after the negotiation with the remote peer. In a batch of channel openings
     *          this flag should be set to true for every channel but the very last.
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Rpc::initOnce();
        parent::__construct($data);
    }

    /**
     *A unique identifier of 32 random bytes that will be used as the pending
     *channel ID to identify the PSBT state machine when interacting with it and
     *on the wire protocol to initiate the funding request.
     *
     * Generated from protobuf field <code>bytes pending_chan_id = 1;</code>
     * @return string
     */
    public function getPendingChanId()
    {
        return $this->pending_chan_id;
    }

    /**
     *A unique identifier of 32 random bytes that will be used as the pending
     *channel ID to identify the PSBT state machine when interacting with it and
     *on the wire protocol to initiate the funding request.
     *
     * Generated from protobuf field <code>bytes pending_chan_id = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setPendingChanId($var)
    {
        GPBUtil::checkString($var, False);
        $this->pending_chan_id = $var;

        return $this;
    }

    /**
     *An optional base PSBT the new channel output will be added to. If this is
     *non-empty, it must be a binary serialized PSBT.
     *
     * Generated from protobuf field <code>bytes base_psbt = 2;</code>
     * @return string
     */
    public function getBasePsbt()
    {
        return $this->base_psbt;
    }

    /**
     *An optional base PSBT the new channel output will be added to. If this is
     *non-empty, it must be a binary serialized PSBT.
     *
     * Generated from protobuf field <code>bytes base_psbt = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setBasePsbt($var)
    {
        GPBUtil::checkString($var, False);
        $this->base_psbt = $var;

        return $this;
    }

    /**
     *If a channel should be part of a batch (multiple channel openings in one
     *transaction), it can be dangerous if the whole batch transaction is
     *published too early before all channel opening negotiations are completed.
     *This flag prevents this particular channel from broadcasting the transaction
     *after the negotiation with the remote peer. In a batch of channel openings
     *this flag should be set to true for every channel but the very last.
     *
     * Generated from protobuf field <code>bool no_publish = 3;</code>
     * @return bool
     */
    public function getNoPublish()
    {
        return $this->no_publish;
    }

    /**
     *If a channel should be part of a batch (multiple channel openings in one
     *transaction), it can be dangerous if the whole batch transaction is
     *published too early before all channel opening negotiations are completed.
     *This flag prevents this particular channel from broadcasting the transaction
     *after the negotiation with the remote peer. In a batch of channel openings
     *this flag should be set to true for every channel but the very last.
     *
     * Generated from protobuf field <code>bool no_publish = 3;</code>
     * @param bool $var
     * @return $this
     */
    public function setNoPublish($var)
    {
        GPBUtil::checkBool($var);
        $this->no_publish = $var;

        return $this;
    }

}

