<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: rpc.proto

namespace Lnrpc;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>lnrpc.SendResponse</code>
 */
class SendResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string payment_error = 1;</code>
     */
    protected $payment_error = '';
    /**
     * Generated from protobuf field <code>bytes payment_preimage = 2;</code>
     */
    protected $payment_preimage = '';
    /**
     * Generated from protobuf field <code>.lnrpc.Route payment_route = 3;</code>
     */
    protected $payment_route = null;
    /**
     * Generated from protobuf field <code>bytes payment_hash = 4;</code>
     */
    protected $payment_hash = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $payment_error
     *     @type string $payment_preimage
     *     @type \Lnrpc\Route $payment_route
     *     @type string $payment_hash
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Rpc::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string payment_error = 1;</code>
     * @return string
     */
    public function getPaymentError()
    {
        return $this->payment_error;
    }

    /**
     * Generated from protobuf field <code>string payment_error = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setPaymentError($var)
    {
        GPBUtil::checkString($var, True);
        $this->payment_error = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bytes payment_preimage = 2;</code>
     * @return string
     */
    public function getPaymentPreimage()
    {
        return $this->payment_preimage;
    }

    /**
     * Generated from protobuf field <code>bytes payment_preimage = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setPaymentPreimage($var)
    {
        GPBUtil::checkString($var, False);
        $this->payment_preimage = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.lnrpc.Route payment_route = 3;</code>
     * @return \Lnrpc\Route
     */
    public function getPaymentRoute()
    {
        return isset($this->payment_route) ? $this->payment_route : null;
    }

    public function hasPaymentRoute()
    {
        return isset($this->payment_route);
    }

    public function clearPaymentRoute()
    {
        unset($this->payment_route);
    }

    /**
     * Generated from protobuf field <code>.lnrpc.Route payment_route = 3;</code>
     * @param \Lnrpc\Route $var
     * @return $this
     */
    public function setPaymentRoute($var)
    {
        GPBUtil::checkMessage($var, \Lnrpc\Route::class);
        $this->payment_route = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bytes payment_hash = 4;</code>
     * @return string
     */
    public function getPaymentHash()
    {
        return $this->payment_hash;
    }

    /**
     * Generated from protobuf field <code>bytes payment_hash = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setPaymentHash($var)
    {
        GPBUtil::checkString($var, False);
        $this->payment_hash = $var;

        return $this;
    }

}

