<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: lightning.proto

namespace Lnrpc;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>lnrpc.StreamAuth</code>
 */
class StreamAuth extends \Google\Protobuf\Internal\Message
{
    /**
     *The full URI (in the format /<rpcpackage>.<ServiceName>/MethodName, for
     *example /lnrpc.Lightning/GetInfo) of the streaming RPC method that was just
     *established.
     *
     * Generated from protobuf field <code>string method_full_uri = 1;</code>
     */
    protected $method_full_uri = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $method_full_uri
     *          The full URI (in the format /<rpcpackage>.<ServiceName>/MethodName, for
     *          example /lnrpc.Lightning/GetInfo) of the streaming RPC method that was just
     *          established.
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Lightning::initOnce();
        parent::__construct($data);
    }

    /**
     *The full URI (in the format /<rpcpackage>.<ServiceName>/MethodName, for
     *example /lnrpc.Lightning/GetInfo) of the streaming RPC method that was just
     *established.
     *
     * Generated from protobuf field <code>string method_full_uri = 1;</code>
     * @return string
     */
    public function getMethodFullUri()
    {
        return $this->method_full_uri;
    }

    /**
     *The full URI (in the format /<rpcpackage>.<ServiceName>/MethodName, for
     *example /lnrpc.Lightning/GetInfo) of the streaming RPC method that was just
     *established.
     *
     * Generated from protobuf field <code>string method_full_uri = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setMethodFullUri($var)
    {
        GPBUtil::checkString($var, True);
        $this->method_full_uri = $var;

        return $this;
    }

}

