<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: rpc.proto

namespace Lnrpc;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>lnrpc.Transaction</code>
 */
class Transaction extends \Google\Protobuf\Internal\Message
{
    /**
     * The transaction hash
     *
     * Generated from protobuf field <code>string tx_hash = 1;</code>
     */
    private $tx_hash = '';
    /**
     * The transaction amount, denominated in satoshis
     *
     * Generated from protobuf field <code>int64 amount = 2;</code>
     */
    private $amount = 0;
    /**
     * The number of confirmations
     *
     * Generated from protobuf field <code>int32 num_confirmations = 3;</code>
     */
    private $num_confirmations = 0;
    /**
     * The hash of the block this transaction was included in
     *
     * Generated from protobuf field <code>string block_hash = 4;</code>
     */
    private $block_hash = '';
    /**
     * The height of the block this transaction was included in
     *
     * Generated from protobuf field <code>int32 block_height = 5;</code>
     */
    private $block_height = 0;
    /**
     * Timestamp of this transaction
     *
     * Generated from protobuf field <code>int64 time_stamp = 6;</code>
     */
    private $time_stamp = 0;
    /**
     * Fees paid for this transaction
     *
     * Generated from protobuf field <code>int64 total_fees = 7;</code>
     */
    private $total_fees = 0;
    /**
     * Addresses that received funds for this transaction
     *
     * Generated from protobuf field <code>repeated string dest_addresses = 8;</code>
     */
    private $dest_addresses;
    /**
     * The raw transaction hex.
     *
     * Generated from protobuf field <code>string raw_tx_hex = 9;</code>
     */
    private $raw_tx_hex = '';
    /**
     * A label that was optionally set on transaction broadcast.
     *
     * Generated from protobuf field <code>string label = 10;</code>
     */
    private $label = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $tx_hash
     *           The transaction hash
     *     @type int|string $amount
     *           The transaction amount, denominated in satoshis
     *     @type int $num_confirmations
     *           The number of confirmations
     *     @type string $block_hash
     *           The hash of the block this transaction was included in
     *     @type int $block_height
     *           The height of the block this transaction was included in
     *     @type int|string $time_stamp
     *           Timestamp of this transaction
     *     @type int|string $total_fees
     *           Fees paid for this transaction
     *     @type string[]|\Google\Protobuf\Internal\RepeatedField $dest_addresses
     *           Addresses that received funds for this transaction
     *     @type string $raw_tx_hex
     *           The raw transaction hex.
     *     @type string $label
     *           A label that was optionally set on transaction broadcast.
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Rpc::initOnce();
        parent::__construct($data);
    }

    /**
     * The transaction hash
     *
     * Generated from protobuf field <code>string tx_hash = 1;</code>
     * @return string
     */
    public function getTxHash()
    {
        return $this->tx_hash;
    }

    /**
     * The transaction hash
     *
     * Generated from protobuf field <code>string tx_hash = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setTxHash($var)
    {
        GPBUtil::checkString($var, True);
        $this->tx_hash = $var;

        return $this;
    }

    /**
     * The transaction amount, denominated in satoshis
     *
     * Generated from protobuf field <code>int64 amount = 2;</code>
     * @return int|string
     */
    public function getAmount()
    {
        return $this->amount;
    }

    /**
     * The transaction amount, denominated in satoshis
     *
     * Generated from protobuf field <code>int64 amount = 2;</code>
     * @param int|string $var
     * @return $this
     */
    public function setAmount($var)
    {
        GPBUtil::checkInt64($var);
        $this->amount = $var;

        return $this;
    }

    /**
     * The number of confirmations
     *
     * Generated from protobuf field <code>int32 num_confirmations = 3;</code>
     * @return int
     */
    public function getNumConfirmations()
    {
        return $this->num_confirmations;
    }

    /**
     * The number of confirmations
     *
     * Generated from protobuf field <code>int32 num_confirmations = 3;</code>
     * @param int $var
     * @return $this
     */
    public function setNumConfirmations($var)
    {
        GPBUtil::checkInt32($var);
        $this->num_confirmations = $var;

        return $this;
    }

    /**
     * The hash of the block this transaction was included in
     *
     * Generated from protobuf field <code>string block_hash = 4;</code>
     * @return string
     */
    public function getBlockHash()
    {
        return $this->block_hash;
    }

    /**
     * The hash of the block this transaction was included in
     *
     * Generated from protobuf field <code>string block_hash = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setBlockHash($var)
    {
        GPBUtil::checkString($var, True);
        $this->block_hash = $var;

        return $this;
    }

    /**
     * The height of the block this transaction was included in
     *
     * Generated from protobuf field <code>int32 block_height = 5;</code>
     * @return int
     */
    public function getBlockHeight()
    {
        return $this->block_height;
    }

    /**
     * The height of the block this transaction was included in
     *
     * Generated from protobuf field <code>int32 block_height = 5;</code>
     * @param int $var
     * @return $this
     */
    public function setBlockHeight($var)
    {
        GPBUtil::checkInt32($var);
        $this->block_height = $var;

        return $this;
    }

    /**
     * Timestamp of this transaction
     *
     * Generated from protobuf field <code>int64 time_stamp = 6;</code>
     * @return int|string
     */
    public function getTimeStamp()
    {
        return $this->time_stamp;
    }

    /**
     * Timestamp of this transaction
     *
     * Generated from protobuf field <code>int64 time_stamp = 6;</code>
     * @param int|string $var
     * @return $this
     */
    public function setTimeStamp($var)
    {
        GPBUtil::checkInt64($var);
        $this->time_stamp = $var;

        return $this;
    }

    /**
     * Fees paid for this transaction
     *
     * Generated from protobuf field <code>int64 total_fees = 7;</code>
     * @return int|string
     */
    public function getTotalFees()
    {
        return $this->total_fees;
    }

    /**
     * Fees paid for this transaction
     *
     * Generated from protobuf field <code>int64 total_fees = 7;</code>
     * @param int|string $var
     * @return $this
     */
    public function setTotalFees($var)
    {
        GPBUtil::checkInt64($var);
        $this->total_fees = $var;

        return $this;
    }

    /**
     * Addresses that received funds for this transaction
     *
     * Generated from protobuf field <code>repeated string dest_addresses = 8;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getDestAddresses()
    {
        return $this->dest_addresses;
    }

    /**
     * Addresses that received funds for this transaction
     *
     * Generated from protobuf field <code>repeated string dest_addresses = 8;</code>
     * @param string[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setDestAddresses($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::STRING);
        $this->dest_addresses = $arr;

        return $this;
    }

    /**
     * The raw transaction hex.
     *
     * Generated from protobuf field <code>string raw_tx_hex = 9;</code>
     * @return string
     */
    public function getRawTxHex()
    {
        return $this->raw_tx_hex;
    }

    /**
     * The raw transaction hex.
     *
     * Generated from protobuf field <code>string raw_tx_hex = 9;</code>
     * @param string $var
     * @return $this
     */
    public function setRawTxHex($var)
    {
        GPBUtil::checkString($var, True);
        $this->raw_tx_hex = $var;

        return $this;
    }

    /**
     * A label that was optionally set on transaction broadcast.
     *
     * Generated from protobuf field <code>string label = 10;</code>
     * @return string
     */
    public function getLabel()
    {
        return $this->label;
    }

    /**
     * A label that was optionally set on transaction broadcast.
     *
     * Generated from protobuf field <code>string label = 10;</code>
     * @param string $var
     * @return $this
     */
    public function setLabel($var)
    {
        GPBUtil::checkString($var, True);
        $this->label = $var;

        return $this;
    }

}

