<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: autopilot.proto

namespace Autopilotrpc;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>autopilotrpc.ModifyStatusResponse</code>
 */
class ModifyStatusResponse extends \Google\Protobuf\Internal\Message
{

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Autopilot::initOnce();
        parent::__construct($data);
    }

}

