<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: invoices.proto

namespace Invoicesrpc;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>invoicesrpc.SubscribeSingleInvoiceRequest</code>
 */
class SubscribeSingleInvoiceRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Hash corresponding to the (hold) invoice to subscribe to. When using
     * REST, this field must be encoded as base64url.
     *
     * Generated from protobuf field <code>bytes r_hash = 2;</code>
     */
    protected $r_hash = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $r_hash
     *           Hash corresponding to the (hold) invoice to subscribe to. When using
     *           REST, this field must be encoded as base64url.
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Invoices::initOnce();
        parent::__construct($data);
    }

    /**
     * Hash corresponding to the (hold) invoice to subscribe to. When using
     * REST, this field must be encoded as base64url.
     *
     * Generated from protobuf field <code>bytes r_hash = 2;</code>
     * @return string
     */
    public function getRHash()
    {
        return $this->r_hash;
    }

    /**
     * Hash corresponding to the (hold) invoice to subscribe to. When using
     * REST, this field must be encoded as base64url.
     *
     * Generated from protobuf field <code>bytes r_hash = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setRHash($var)
    {
        GPBUtil::checkString($var, False);
        $this->r_hash = $var;

        return $this;
    }

}

