<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: dev.proto

namespace GPBMetadata;

class Dev
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \GPBMetadata\Lightning::initOnce();
        $pool->internalAddGeneratedFile(
            '
ª
	dev.protodevrpc"
ImportGraphResponse2F
Dev?
ImportGraph.lnrpc.ChannelGraph.devrpc.ImportGraphResponseB.Z,github.com/lightningnetwork/lnd/lnrpc/devrpcbproto3'
        , true);

        static::$is_initialized = true;
    }
}

