<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: verrpc.proto

namespace GPBMetadata;

class Verrpc
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(
            '
à
verrpc.protoverrpc"
VersionRequest"¹
Version
commit (	
commit_hash (	
version (	
	app_major (
	app_minor (
	app_patch (
app_pre_release (	

build_tags (	

go_version	 (	2B
	Versioner5

GetVersion.verrpc.VersionRequest.verrpc.VersionB.Z,github.com/lightningnetwork/lnd/lnrpc/verrpcbproto3'
        , true);

        static::$is_initialized = true;
    }
}

