<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: walletkit.proto

namespace Walletrpc\ListSweepsResponse;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>walletrpc.ListSweepsResponse.TransactionIDs</code>
 */
class TransactionIDs extends \Google\Protobuf\Internal\Message
{
    /**
     *Reversed, hex-encoded string representing the transaction ids of the
     *sweeps that our node has broadcast. Note that these transactions may
     *not have confirmed yet, we record sweeps on broadcast, not confirmation.
     *
     * Generated from protobuf field <code>repeated string transaction_ids = 1;</code>
     */
    private $transaction_ids;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type array<string>|\Google\Protobuf\Internal\RepeatedField $transaction_ids
     *          Reversed, hex-encoded string representing the transaction ids of the
     *          sweeps that our node has broadcast. Note that these transactions may
     *          not have confirmed yet, we record sweeps on broadcast, not confirmation.
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Walletkit::initOnce();
        parent::__construct($data);
    }

    /**
     *Reversed, hex-encoded string representing the transaction ids of the
     *sweeps that our node has broadcast. Note that these transactions may
     *not have confirmed yet, we record sweeps on broadcast, not confirmation.
     *
     * Generated from protobuf field <code>repeated string transaction_ids = 1;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getTransactionIds()
    {
        return $this->transaction_ids;
    }

    /**
     *Reversed, hex-encoded string representing the transaction ids of the
     *sweeps that our node has broadcast. Note that these transactions may
     *not have confirmed yet, we record sweeps on broadcast, not confirmation.
     *
     * Generated from protobuf field <code>repeated string transaction_ids = 1;</code>
     * @param array<string>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setTransactionIds($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::STRING);
        $this->transaction_ids = $arr;

        return $this;
    }

}

// Adding a class alias for backwards compatibility with the previous class name.
class_alias(TransactionIDs::class, \Walletrpc\ListSweepsResponse_TransactionIDs::class);

