<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: walletkit.proto

namespace Walletrpc;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>walletrpc.AccountWithAddresses</code>
 */
class AccountWithAddresses extends \Google\Protobuf\Internal\Message
{
    /**
     * The name used to identify the account.
     *
     * Generated from protobuf field <code>string name = 1;</code>
     */
    protected $name = '';
    /**
     * The type of addresses the account supports.
     *
     * Generated from protobuf field <code>.walletrpc.AddressType address_type = 2;</code>
     */
    protected $address_type = 0;
    /**
     *The derivation path corresponding to the account public key. This will
     *always be empty for the default imported account in which single public keys
     *are imported into.
     *
     * Generated from protobuf field <code>string derivation_path = 3;</code>
     */
    protected $derivation_path = '';
    /**
     *List of address, its type internal/external & balance.
     *Note that the order of addresses will be random and not according to the
     *derivation index, since that information is not stored by the underlying
     *wallet.
     *
     * Generated from protobuf field <code>repeated .walletrpc.AddressProperty addresses = 4;</code>
     */
    private $addresses;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $name
     *           The name used to identify the account.
     *     @type int $address_type
     *           The type of addresses the account supports.
     *     @type string $derivation_path
     *          The derivation path corresponding to the account public key. This will
     *          always be empty for the default imported account in which single public keys
     *          are imported into.
     *     @type array<\Walletrpc\AddressProperty>|\Google\Protobuf\Internal\RepeatedField $addresses
     *          List of address, its type internal/external & balance.
     *          Note that the order of addresses will be random and not according to the
     *          derivation index, since that information is not stored by the underlying
     *          wallet.
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Walletkit::initOnce();
        parent::__construct($data);
    }

    /**
     * The name used to identify the account.
     *
     * Generated from protobuf field <code>string name = 1;</code>
     * @return string
     */
    public function getName()
    {
        return $this->name;
    }

    /**
     * The name used to identify the account.
     *
     * Generated from protobuf field <code>string name = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setName($var)
    {
        GPBUtil::checkString($var, True);
        $this->name = $var;

        return $this;
    }

    /**
     * The type of addresses the account supports.
     *
     * Generated from protobuf field <code>.walletrpc.AddressType address_type = 2;</code>
     * @return int
     */
    public function getAddressType()
    {
        return $this->address_type;
    }

    /**
     * The type of addresses the account supports.
     *
     * Generated from protobuf field <code>.walletrpc.AddressType address_type = 2;</code>
     * @param int $var
     * @return $this
     */
    public function setAddressType($var)
    {
        GPBUtil::checkEnum($var, \Walletrpc\AddressType::class);
        $this->address_type = $var;

        return $this;
    }

    /**
     *The derivation path corresponding to the account public key. This will
     *always be empty for the default imported account in which single public keys
     *are imported into.
     *
     * Generated from protobuf field <code>string derivation_path = 3;</code>
     * @return string
     */
    public function getDerivationPath()
    {
        return $this->derivation_path;
    }

    /**
     *The derivation path corresponding to the account public key. This will
     *always be empty for the default imported account in which single public keys
     *are imported into.
     *
     * Generated from protobuf field <code>string derivation_path = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setDerivationPath($var)
    {
        GPBUtil::checkString($var, True);
        $this->derivation_path = $var;

        return $this;
    }

    /**
     *List of address, its type internal/external & balance.
     *Note that the order of addresses will be random and not according to the
     *derivation index, since that information is not stored by the underlying
     *wallet.
     *
     * Generated from protobuf field <code>repeated .walletrpc.AddressProperty addresses = 4;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getAddresses()
    {
        return $this->addresses;
    }

    /**
     *List of address, its type internal/external & balance.
     *Note that the order of addresses will be random and not according to the
     *derivation index, since that information is not stored by the underlying
     *wallet.
     *
     * Generated from protobuf field <code>repeated .walletrpc.AddressProperty addresses = 4;</code>
     * @param array<\Walletrpc\AddressProperty>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setAddresses($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Walletrpc\AddressProperty::class);
        $this->addresses = $arr;

        return $this;
    }

}

