<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: walletkit.proto

namespace Walletrpc;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>walletrpc.EstimateFeeRequest</code>
 */
class EstimateFeeRequest extends \Google\Protobuf\Internal\Message
{
    /**
     *The number of confirmations to shoot for when estimating the fee.
     *
     * Generated from protobuf field <code>int32 conf_target = 1;</code>
     */
    protected $conf_target = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $conf_target
     *          The number of confirmations to shoot for when estimating the fee.
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Walletkit::initOnce();
        parent::__construct($data);
    }

    /**
     *The number of confirmations to shoot for when estimating the fee.
     *
     * Generated from protobuf field <code>int32 conf_target = 1;</code>
     * @return int
     */
    public function getConfTarget()
    {
        return $this->conf_target;
    }

    /**
     *The number of confirmations to shoot for when estimating the fee.
     *
     * Generated from protobuf field <code>int32 conf_target = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setConfTarget($var)
    {
        GPBUtil::checkInt32($var);
        $this->conf_target = $var;

        return $this;
    }

}

