<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: walletkit.proto

namespace Walletrpc;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>walletrpc.LeaseOutputResponse</code>
 */
class LeaseOutputResponse extends \Google\Protobuf\Internal\Message
{
    /**
     *The absolute expiration of the output lease represented as a unix timestamp.
     *
     * Generated from protobuf field <code>uint64 expiration = 1;</code>
     */
    private $expiration = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int|string $expiration
     *          The absolute expiration of the output lease represented as a unix timestamp.
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Walletkit::initOnce();
        parent::__construct($data);
    }

    /**
     *The absolute expiration of the output lease represented as a unix timestamp.
     *
     * Generated from protobuf field <code>uint64 expiration = 1;</code>
     * @return int|string
     */
    public function getExpiration()
    {
        return $this->expiration;
    }

    /**
     *The absolute expiration of the output lease represented as a unix timestamp.
     *
     * Generated from protobuf field <code>uint64 expiration = 1;</code>
     * @param int|string $var
     * @return $this
     */
    public function setExpiration($var)
    {
        GPBUtil::checkUint64($var);
        $this->expiration = $var;

        return $this;
    }

}

