<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: walletkit.proto

namespace Walletrpc;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>walletrpc.SignPsbtResponse</code>
 */
class SignPsbtResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * The signed transaction in PSBT format.
     *
     * Generated from protobuf field <code>bytes signed_psbt = 1;</code>
     */
    protected $signed_psbt = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $signed_psbt
     *           The signed transaction in PSBT format.
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Walletkit::initOnce();
        parent::__construct($data);
    }

    /**
     * The signed transaction in PSBT format.
     *
     * Generated from protobuf field <code>bytes signed_psbt = 1;</code>
     * @return string
     */
    public function getSignedPsbt()
    {
        return $this->signed_psbt;
    }

    /**
     * The signed transaction in PSBT format.
     *
     * Generated from protobuf field <code>bytes signed_psbt = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setSignedPsbt($var)
    {
        GPBUtil::checkString($var, False);
        $this->signed_psbt = $var;

        return $this;
    }

}

