<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: walletkit.proto

namespace Walletrpc;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>walletrpc.TapLeaf</code>
 */
class TapLeaf extends \Google\Protobuf\Internal\Message
{
    /**
     * The leaf version. Should be 0xc0 (192) in case of a SegWit v1 script.
     *
     * Generated from protobuf field <code>uint32 leaf_version = 1;</code>
     */
    protected $leaf_version = 0;
    /**
     * The script of the tap leaf.
     *
     * Generated from protobuf field <code>bytes script = 2;</code>
     */
    protected $script = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $leaf_version
     *           The leaf version. Should be 0xc0 (192) in case of a SegWit v1 script.
     *     @type string $script
     *           The script of the tap leaf.
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Walletkit::initOnce();
        parent::__construct($data);
    }

    /**
     * The leaf version. Should be 0xc0 (192) in case of a SegWit v1 script.
     *
     * Generated from protobuf field <code>uint32 leaf_version = 1;</code>
     * @return int
     */
    public function getLeafVersion()
    {
        return $this->leaf_version;
    }

    /**
     * The leaf version. Should be 0xc0 (192) in case of a SegWit v1 script.
     *
     * Generated from protobuf field <code>uint32 leaf_version = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setLeafVersion($var)
    {
        GPBUtil::checkUint32($var);
        $this->leaf_version = $var;

        return $this;
    }

    /**
     * The script of the tap leaf.
     *
     * Generated from protobuf field <code>bytes script = 2;</code>
     * @return string
     */
    public function getScript()
    {
        return $this->script;
    }

    /**
     * The script of the tap leaf.
     *
     * Generated from protobuf field <code>bytes script = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setScript($var)
    {
        GPBUtil::checkString($var, False);
        $this->script = $var;

        return $this;
    }

}

