<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: signer.proto

namespace Signrpc;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>signrpc.InputScript</code>
 */
class InputScript extends \Google\Protobuf\Internal\Message
{
    /**
     *&#47; The serializes witness stack for the specified input.
     *
     * Generated from protobuf field <code>repeated bytes witness = 1;</code>
     */
    private $witness;
    /**
     ***
     *The optional sig script for the specified witness that will only be set if
     *the input specified is a nested p2sh witness program.
     *
     * Generated from protobuf field <code>bytes sig_script = 2;</code>
     */
    private $sig_script = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string[]|\Google\Protobuf\Internal\RepeatedField $witness
     *          &#47; The serializes witness stack for the specified input.
     *     @type string $sig_script
     *          **
     *          The optional sig script for the specified witness that will only be set if
     *          the input specified is a nested p2sh witness program.
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Signer::initOnce();
        parent::__construct($data);
    }

    /**
     *&#47; The serializes witness stack for the specified input.
     *
     * Generated from protobuf field <code>repeated bytes witness = 1;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getWitness()
    {
        return $this->witness;
    }

    /**
     *&#47; The serializes witness stack for the specified input.
     *
     * Generated from protobuf field <code>repeated bytes witness = 1;</code>
     * @param string[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setWitness($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::BYTES);
        $this->witness = $arr;

        return $this;
    }

    /**
     ***
     *The optional sig script for the specified witness that will only be set if
     *the input specified is a nested p2sh witness program.
     *
     * Generated from protobuf field <code>bytes sig_script = 2;</code>
     * @return string
     */
    public function getSigScript()
    {
        return $this->sig_script;
    }

    /**
     ***
     *The optional sig script for the specified witness that will only be set if
     *the input specified is a nested p2sh witness program.
     *
     * Generated from protobuf field <code>bytes sig_script = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setSigScript($var)
    {
        GPBUtil::checkString($var, False);
        $this->sig_script = $var;

        return $this;
    }

}

