<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: signer.proto

namespace Signrpc;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>signrpc.MuSig2RegisterNoncesRequest</code>
 */
class MuSig2RegisterNoncesRequest extends \Google\Protobuf\Internal\Message
{
    /**
     *The unique ID of the signing session those nonces should be registered with.
     *
     * Generated from protobuf field <code>bytes session_id = 1;</code>
     */
    protected $session_id = '';
    /**
     *A list of all public nonces of other signing participants that should be
     *registered.
     *
     * Generated from protobuf field <code>repeated bytes other_signer_public_nonces = 3;</code>
     */
    private $other_signer_public_nonces;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $session_id
     *          The unique ID of the signing session those nonces should be registered with.
     *     @type array<string>|\Google\Protobuf\Internal\RepeatedField $other_signer_public_nonces
     *          A list of all public nonces of other signing participants that should be
     *          registered.
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Signer::initOnce();
        parent::__construct($data);
    }

    /**
     *The unique ID of the signing session those nonces should be registered with.
     *
     * Generated from protobuf field <code>bytes session_id = 1;</code>
     * @return string
     */
    public function getSessionId()
    {
        return $this->session_id;
    }

    /**
     *The unique ID of the signing session those nonces should be registered with.
     *
     * Generated from protobuf field <code>bytes session_id = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setSessionId($var)
    {
        GPBUtil::checkString($var, False);
        $this->session_id = $var;

        return $this;
    }

    /**
     *A list of all public nonces of other signing participants that should be
     *registered.
     *
     * Generated from protobuf field <code>repeated bytes other_signer_public_nonces = 3;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getOtherSignerPublicNonces()
    {
        return $this->other_signer_public_nonces;
    }

    /**
     *A list of all public nonces of other signing participants that should be
     *registered.
     *
     * Generated from protobuf field <code>repeated bytes other_signer_public_nonces = 3;</code>
     * @param array<string>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setOtherSignerPublicNonces($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::BYTES);
        $this->other_signer_public_nonces = $arr;

        return $this;
    }

}

