<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: signer.proto

namespace Signrpc;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>signrpc.SharedKeyRequest</code>
 */
class SharedKeyRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * The ephemeral public key to use for the DH key derivation.
     *
     * Generated from protobuf field <code>bytes ephemeral_pubkey = 1;</code>
     */
    private $ephemeral_pubkey = '';
    /**
     **
     *The optional key locator of the local key that should be used. If this
     *parameter is not set then the node's identity private key will be used.
     *
     * Generated from protobuf field <code>.signrpc.KeyLocator key_loc = 2;</code>
     */
    private $key_loc = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $ephemeral_pubkey
     *           The ephemeral public key to use for the DH key derivation.
     *     @type \Signrpc\KeyLocator $key_loc
     *          *
     *          The optional key locator of the local key that should be used. If this
     *          parameter is not set then the node's identity private key will be used.
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Signer::initOnce();
        parent::__construct($data);
    }

    /**
     * The ephemeral public key to use for the DH key derivation.
     *
     * Generated from protobuf field <code>bytes ephemeral_pubkey = 1;</code>
     * @return string
     */
    public function getEphemeralPubkey()
    {
        return $this->ephemeral_pubkey;
    }

    /**
     * The ephemeral public key to use for the DH key derivation.
     *
     * Generated from protobuf field <code>bytes ephemeral_pubkey = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setEphemeralPubkey($var)
    {
        GPBUtil::checkString($var, False);
        $this->ephemeral_pubkey = $var;

        return $this;
    }

    /**
     **
     *The optional key locator of the local key that should be used. If this
     *parameter is not set then the node's identity private key will be used.
     *
     * Generated from protobuf field <code>.signrpc.KeyLocator key_loc = 2;</code>
     * @return \Signrpc\KeyLocator
     */
    public function getKeyLoc()
    {
        return $this->key_loc;
    }

    /**
     **
     *The optional key locator of the local key that should be used. If this
     *parameter is not set then the node's identity private key will be used.
     *
     * Generated from protobuf field <code>.signrpc.KeyLocator key_loc = 2;</code>
     * @param \Signrpc\KeyLocator $var
     * @return $this
     */
    public function setKeyLoc($var)
    {
        GPBUtil::checkMessage($var, \Signrpc\KeyLocator::class);
        $this->key_loc = $var;

        return $this;
    }

}

