<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: router.proto

namespace Routerrpc\MissionControlConfig;

use UnexpectedValueException;

/**
 * Protobuf type <code>routerrpc.MissionControlConfig.ProbabilityModel</code>
 */
class ProbabilityModel
{
    /**
     * Generated from protobuf enum <code>APRIORI = 0;</code>
     */
    const APRIORI = 0;
    /**
     * Generated from protobuf enum <code>BIMODAL = 1;</code>
     */
    const BIMODAL = 1;

    private static $valueToName = [
        self::APRIORI => 'APRIORI',
        self::BIMODAL => 'BIMODAL',
    ];

    public static function name($value)
    {
        if (!isset(self::$valueToName[$value])) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no name defined for value %s', __CLASS__, $value));
        }
        return self::$valueToName[$value];
    }


    public static function value($name)
    {
        $const = __CLASS__ . '::' . strtoupper($name);
        if (!defined($const)) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no value defined for name %s', __CLASS__, $name));
        }
        return constant($const);
    }
}

// Adding a class alias for backwards compatibility with the previous class name.
class_alias(ProbabilityModel::class, \Routerrpc\MissionControlConfig_ProbabilityModel::class);

