<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: router.proto

namespace Routerrpc;

use UnexpectedValueException;

/**
 * Protobuf type <code>routerrpc.ResolveHoldForwardAction</code>
 */
class ResolveHoldForwardAction
{
    /**
     * Generated from protobuf enum <code>SETTLE = 0;</code>
     */
    const SETTLE = 0;
    /**
     * Generated from protobuf enum <code>FAIL = 1;</code>
     */
    const FAIL = 1;
    /**
     * Generated from protobuf enum <code>RESUME = 2;</code>
     */
    const RESUME = 2;

    private static $valueToName = [
        self::SETTLE => 'SETTLE',
        self::FAIL => 'FAIL',
        self::RESUME => 'RESUME',
    ];

    public static function name($value)
    {
        if (!isset(self::$valueToName[$value])) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no name defined for value %s', __CLASS__, $value));
        }
        return self::$valueToName[$value];
    }


    public static function value($name)
    {
        $const = __CLASS__ . '::' . strtoupper($name);
        if (!defined($const)) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no value defined for name %s', __CLASS__, $name));
        }
        return constant($const);
    }
}

