<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: router.proto

namespace Routerrpc;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>routerrpc.XImportMissionControlRequest</code>
 */
class XImportMissionControlRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Node pair-level mission control state to be imported.
     *
     * Generated from protobuf field <code>repeated .routerrpc.PairHistory pairs = 1;</code>
     */
    private $pairs;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Routerrpc\PairHistory[]|\Google\Protobuf\Internal\RepeatedField $pairs
     *           Node pair-level mission control state to be imported.
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Router::initOnce();
        parent::__construct($data);
    }

    /**
     * Node pair-level mission control state to be imported.
     *
     * Generated from protobuf field <code>repeated .routerrpc.PairHistory pairs = 1;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getPairs()
    {
        return $this->pairs;
    }

    /**
     * Node pair-level mission control state to be imported.
     *
     * Generated from protobuf field <code>repeated .routerrpc.PairHistory pairs = 1;</code>
     * @param \Routerrpc\PairHistory[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setPairs($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Routerrpc\PairHistory::class);
        $this->pairs = $arr;

        return $this;
    }

}

