<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: wtclient.proto

namespace Wtclientrpc;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>wtclientrpc.GetTowerInfoRequest</code>
 */
class GetTowerInfoRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * The identifying public key of the watchtower to retrieve information for.
     *
     * Generated from protobuf field <code>bytes pubkey = 1;</code>
     */
    protected $pubkey = '';
    /**
     * Whether we should include sessions with the watchtower in the response.
     *
     * Generated from protobuf field <code>bool include_sessions = 2;</code>
     */
    protected $include_sessions = false;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $pubkey
     *           The identifying public key of the watchtower to retrieve information for.
     *     @type bool $include_sessions
     *           Whether we should include sessions with the watchtower in the response.
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Wtclient::initOnce();
        parent::__construct($data);
    }

    /**
     * The identifying public key of the watchtower to retrieve information for.
     *
     * Generated from protobuf field <code>bytes pubkey = 1;</code>
     * @return string
     */
    public function getPubkey()
    {
        return $this->pubkey;
    }

    /**
     * The identifying public key of the watchtower to retrieve information for.
     *
     * Generated from protobuf field <code>bytes pubkey = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setPubkey($var)
    {
        GPBUtil::checkString($var, False);
        $this->pubkey = $var;

        return $this;
    }

    /**
     * Whether we should include sessions with the watchtower in the response.
     *
     * Generated from protobuf field <code>bool include_sessions = 2;</code>
     * @return bool
     */
    public function getIncludeSessions()
    {
        return $this->include_sessions;
    }

    /**
     * Whether we should include sessions with the watchtower in the response.
     *
     * Generated from protobuf field <code>bool include_sessions = 2;</code>
     * @param bool $var
     * @return $this
     */
    public function setIncludeSessions($var)
    {
        GPBUtil::checkBool($var);
        $this->include_sessions = $var;

        return $this;
    }

}

